services:
  app:
    build:
      context: .
      target: production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - production-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.26-alpine
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    depends_on:
      - app
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template

volumes:
  production-pgdata:
