services:
  app:
    build:
      context: .
      target: development
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - nmdata:/usr/src/app/node_modules

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  nmdata:
  pgdata:
